# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore ChatBot.sln
      
    - name: Install dotnet-format
      run: dotnet tool install --global dotnet-format
    - name: Check code formatting
      run: dotnet format --verify-no-changes

    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
